Repository IU-Capstone-Project-2024/MoniDorm, pull requests merged in 2024-06, with the labels that each got.

#8 Filter with token
  pom.xml
  src/main/java/com/java/api/ApiExceptionHandler.java
  src/main/java/com/java/api/exception/MissingOrIncorrectAuthorizationHeaderException.java
  src/main/java/com/java/api/filter/AuthorizationFilter.java
  src/main/java/com/java/configuration/FilterConfiguration.java
  src/test/java/com/java/api/filter/AuthorizationFilterTest.java
Labels: backend, feature

#18 DB Connection
  .env.example
  .mvn/maven.config
  .mvn/wrapper/maven-wrapper.properties
  compose.yml
  db/migrations/db.master-changelog.xml
  db/migrations/init/changelog.xml
  db/migrations/init/report-table-init.sql
  src/main/java/com/java/api/AdminPanelAPI.java
  src/main/java/com/java/api/AdminPanelController.java
  src/main/java/com/java/api/ReportAPI.java
  src/main/java/com/java/api/ReportController.java
  src/main/java/com/java/api/exception/NotFoundException.java
  src/main/java/com/java/api/model/GetReportResponse.java
  src/main/java/com/java/api/model/PostProcessReportRequest.java
  src/main/java/com/java/configuration/JpaDatabaseAccessConfiguration.java
  src/main/java/com/java/domain/model/Report.java
  src/main/java/com/java/domain/model/converter/DateTimeConverter.java
  src/main/java/com/java/domain/repository/ReportRepository.java
  src/main/java/com/java/domain/service/ReportService.java
  src/main/java/com/java/domain/service/jpa/JpaReportService.java
  src/main/java/com/java/utils/DateTimeUtils.java
  src/main/resources/application.yml
  src/test/java/com/java/IntegrationEnvironment.java
  src/test/java/com/java/IntegrationEnvironmentHealthcheckTest.java
  src/test/java/com/java/domain/model/converter/DateTimeConverterTest.java
  src/test/java/com/java/domain/service/jpa/JpaReportServiceTest.java
Labels: backend, feature

#19 Implementation of API: Ver 1.0
  Dockerfile
  compose.yml
  pom.xml
  src/main/java/com/java/api/AdminPanelAPI.java
  src/main/java/com/java/api/AdminPanelController.java
  src/main/java/com/java/api/ApiExceptionHandler.java
  src/main/java/com/java/api/ReportAPI.java
  src/main/java/com/java/api/ReportController.java
  src/main/java/com/java/api/exception/NotFoundException.java
  src/main/java/com/java/api/filter/AuthorizationTokenFilter.java
  src/main/java/com/java/api/model/GetReportListResponse.java
  src/main/java/com/java/api/model/GetReportResponse.java
  src/main/java/com/java/configuration/FilterConfiguration.java
  src/main/java/com/java/domain/model/Report.java
  src/main/java/com/java/domain/service/jpa/JpaReportService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/java/api/filter/AuthorizationTokenFilterTest.java
Labels: backend, feature, architecture

#27 Feature/api refactoring
  src/main/java/com/java/api/ReportAPI.java
  src/main/java/com/java/api/ReportController.java
  src/main/java/com/java/domain/service/ReportService.java
  src/main/java/com/java/domain/service/jpa/JpaReportService.java
  src/test/java/com/java/domain/service/jpa/JpaReportServiceTest.java
Labels: feature

#33 Feature/python analyst endpoint
  src/main/java/com/java/api/AnalystSystemAPI.java
  src/main/java/com/java/api/AnalystSystemController.java
  src/main/java/com/java/api/model/PostFailureConfirmationByAnalyticSystemRequest.java
Labels: backend, feature

#30 Set up Docker & Docker Compose for Bot and MongoDB
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  telegram-bot/.env
  telegram-bot/.env.example
  telegram-bot/main.py
Labels: fix, feature, telegram-bot
